version: '3.8'

services:
  http-basic-auth-server:
    build:
      context: .
      args:
        STU_ID: "${STU_ID:-CSIE-NPU}"
    container_name: http-basic-auth-server
    ports:
      - "3128:3128"
    environment:
      - STU_ID=${STU_ID:-CSIE-NPU}
    volumes:
      - ./assets:/app/assets:ro
    restart: unless-stopped
